import {
  Banknote,
  Boxes,
  Briefcase,
  Building2,
  Car,
  Code,
  Compass,
  Cpu,
  GraduationCap,
  HardHat,
  HeartHandshake,
  HeartPulse,
  Landmark,
  MapPin,
  Megaphone,
  MonitorSmartphone,
  Newspaper,
  Package,
  Palette,
  PenTool,
  Plane,
  Search,
  ShoppingBag,
  Sparkles,
  Store,
  Target,
  TrendingUp,
  Trophy,
  Users,
  Workflow,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * Icons referenced by name from the content files in src/data so that the data stays
 * plain and serializable.
 */
export const icons = {
  banknote: Banknote,
  boxes: Boxes,
  briefcase: Briefcase,
  building: Building2,
  car: Car,
  code: Code,
  compass: Compass,
  cpu: Cpu,
  'graduation-cap': GraduationCap,
  'hard-hat': HardHat,
  'heart-handshake': HeartHandshake,
  'heart-pulse': HeartPulse,
  landmark: Landmark,
  'map-pin': MapPin,
  megaphone: Megaphone,
  'monitor-smartphone': MonitorSmartphone,
  newspaper: Newspaper,
  package: Package,
  palette: Palette,
  'pen-tool': PenTool,
  plane: Plane,
  search: Search,
  'shopping-bag': ShoppingBag,
  sparkles: Sparkles,
  store: Store,
  target: Target,
  'trending-up': TrendingUp,
  trophy: Trophy,
  users: Users,
  workflow: Workflow,
  zap: Zap,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof icons
